fix deploy

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -47,14 +47,13 @@ runs:
       if: ${{ github.event.inputs.remote-password ==  '' && github.event.inputs.remote-ssh-key-content == '' && github.event.inputs.remote-ssh-key-file == '' }}
       shell: bash
       run: | 
-        echo "::error ::No remote SSH key or password was provided"
-        exit 1
+        echo "::error ::No remote SSH key or password was provided" && exit 1
 
     - name: Check if plugin artifact is a jar file
       shell: bash
       run: |
         shopt -s nocasematch
-        if [[ ! "${{ github.event.inputs.local-plugin-file }}" =~ \.jar$ ]]; then
+        if [[ ! ${{ github.event.inputs.local-plugin-file }} =~ \.jar$ ]]; then
           echo "::error ::Plugin is not a jar file" && exit 1
         fi 
 
